#!/bin/bash

cat <<EOF

Commands:
  create <host> [--ca <ca>]     Create and sign a new certificate
  get <host>                    Output a certificate
  initca <ca>                   Initialise a new CA
EOF