#!/bin/bash

ca="$1"
ca_root="$ca_home/$ca"

if [ -d "$ca_root" ]; then
  echo "CA $ca_root already exists"
  exit 1
fi

script_root="$(pwd)"

# Create CA root directory
mkdir -p "$ca_root"
# Switch to CA root directory
cd "$ca_root"

# Create required files
mkdir -p certs crl
touch index.txt
echo 01 > serial
echo 01 > crlnumber

ca_private_root="$ca_private/$ca"
# Create private store
if [ ! -x "$ca_private_root" ]; then
  mkdir -p "$ca_private_root"
fi

# Create config files
cat "$script_root/.default_ca/default-config.cnf" > "ca-openssl.cnf"

# Create the CA signing key
openssl genrsa -aes256 -out "$ca_private_root/$ca-private.key" 4096

# Write-protect the key
chmod 400 "$ca_private_root/$ca-private.key"

# Create the CA intermediate certificate
openssl req -new -x509 \
  -out "$ca-ca.crt" \
  -key "$ca_private_root/$ca-private.key" \
  -config "ca-openssl.cnf" \
  -extensions x509v3_CA \
  -days 3650

echo CA $ca created.
