#!/bin/bash

ca="$1"
ca_root="$ca_home/$ca"

if [ -d "$ca_root" ]; then
  echo "CA $ca_root already exists"
  exit 1
fi

script_root="$(pwd)"

# Create CA root directory
mkdir -p "$ca_root"
# Switch to CA root directory
cd "$ca_root"

# Create required files
mkdir -p certs crl
touch index.txt
echo 01 > serial
echo 01 > crlnumber

# Create private store
if [ ! -x "$ca_private/$ca" ]; then
  mkdir -p "$ca_private/$ca"
fi
# Create link to private home
ln -s "$ca_private/$ca" ".private"

# Create config files
cat "$script_root/.default_ca/default-config.cnf" > "ca-openssl.cnf"

# Create the CA signing key
openssl genrsa -aes256 -out ".private/$ca-private.key" 4096

# Create the CA intermediate CSR
openssl req -new -x509 \
  -out "$ca-ca.crt" \
  -key ".private/$ca-private.key" \
  -config "ca-openssl.cnf" \
  -extensions x509v3_CA \
  -days 3650

# Ensure any set password is removed
unset pw
# Remove the symlink
rm ".private"

echo CA $ca created.