name: Create Certificate
on:
  push:
jobs:
  create_csr:
    name: Create CSR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Read file
        id: readfile
        run: echo "fqdn=$(cat hosts/testhost/testhost.yaml | yq '.fqdn')" >> "$GITHUB_OUTPUT"
      - name: Print FQDN
        run: echo "${{ steps.readfile.outputs.fqdn }}"
      - name: Create key
        run: openssl genrsa -out hosts/testhost/key.pem 2048
      - name: Create CSR
        run: openssl req -new -key hosts/testhost/key.pem -out hosts/testhost/${{ steps.readfile.outputs.fqdn }}.csr -config .default_ca/default-config.cnf -subj "/CN=${{ steps.readfile.outputs.fqdn }}\/emailAddress=admin@${{ steps.readfile.outputs.fqdn }}/C=UK/ST=Hampshire/L=Winchester/O=Essar Software/OU=Hazelnet"
      - name: Commit CSR
        uses: EndBug/add-and-commit@v9.1.4
        with:
          add: hosts/testhost/${{ steps.readfile.outputs.fqdn }}.csr
          author_name: Steve
          author_email: steve.roberts@essarsoftware.co.uk
          fetch: false
          message: "Create CSR for ${{ steps.readfile.outputs.fqdn }}"
#  sign_csr:
#    name: Sign CSR
#    runs-on: ubuntu-latest
#  cleanup:
#    name: Cleanup
#    runs-on: ubuntu-latest
