name: Create Certificate
on:
  push:
jobs:
  create_csr:
    name: Create CSR
    runs-on: ubuntu-latest
    env:
      host: testhost
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Read file
        id: readfile
        run: echo "fqdn=$(cat hosts/${{ env.host }}/${{ env.host }}.yaml | yq '.fqdn')" >> "$GITHUB_OUTPUT"
      - name: Print FQDN
        run: echo "${{ steps.readfile.outputs.fqdn }}"
      - name: Create key
        run: openssl genrsa -out hosts/${{ env.host }}/key.pem 2048
      - name: Save key
        uses: actions/upload-artifact@v4
        with:
          name: private-key
          path: hosts/${{ env.host }}/key.pem
          retention-days: 3
      - name: Create CSR
        run: openssl req -new -key hosts/${{ env.host }}/key.pem -out hosts/${{ env.host }}/${{ env.host }}-${{ github.run_id}}.csr -config .default_ca/default-config.cnf -subj "/CN=${{ steps.readfile.outputs.fqdn }}\/emailAddress=admin@${{ steps.readfile.outputs.fqdn }}/C=UK/ST=Hampshire/L=Winchester/O=Essar Software/OU=Hazelnet"
      - name: Save CSR
        uses: actions/upload-artifact@v4
        with:
          name: certificate-signing-request
          path: hosts/${{ env.host }}/${{ env.host }}-${{ github.run_id }}.csr
          retention-days: 3
      
  sign_csr:
    name: Sign CSR
    runs-on: ubuntu-latest
    env:
      ca: default
      host: testhost
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: certificate-signing-request
      - name: Sign certificate
        run: openssl x509 -req -days 365 -in hosts/${{ env.host }}/${{ env.host }}-${{ github.run_id }}.csr -signkey key.pem -out hosts/${{ env.host }}/${{ env.host }}.pem
#
#  cleanup:
#    name: Cleanup
#    runs-on: ubuntu-latest


#- name: Commit CSR
#        uses: EndBug/add-and-commit@v9.1.4
#        with:
#          add: hosts/testhost/${{ steps.readfile.outputs.fqdn }}.csr
#          author_name: Steve
#          author_email: steve.roberts@essarsoftware.co.uk
#          fetch: false
#          message: "Create CSR for ${{ steps.readfile.outputs.fqdn }}"