name: Create Certificate
on:
  push:
    paths:
      - hosts/**
jobs:
  read_config:
    name: Read configuration
    runs-on: ubuntu-latest
    env:
      host: testhost
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Read FQDN
        id: fqdn
        run: echo "fqdn=$(cat hosts/${{ env.host }}/${{ env.host }}.yaml | yq '.fqdn')" >> "$GITHUB_OUTPUT"
      - name: Read CA
        id: ca
        run: echo "ca=$(cat hosts/${{ env.host }}/${{ env.host }}.yaml | yq '.certificate.ca')" >> "$GITHUB_OUTPUT"
      - name: Read days
        id: days
        run: echo "days=$(cat hosts/${{ env.host }}/${{ env.host }}.yaml | yq '.certificate.valid_days')" >> "$GITHUB_OUTPUT"
    outputs:
      ca: ${{ steps.config.ca.ca }}
      days: ${{ steps.config.days.days }}
      fqdn: ${{ steps.config.fqdn.fqdn }}


  sign_csr:
    name: Sign certificate
    runs-on: ubuntu-latest
    needs: read_config
    env:
      host: testhost
      CA_HOME: ca/${{ needs.read_config.outputs.ca }}
      FQDN: ${{ needs.read_config.outputs.fqdn }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Print FQDN
        run: echo "$FQDN"
      - name: Set up CA directory
        run: |
          mkdir -p "$CA_HOME/certs"
          mkdir -p "$CA_HOME/crl"
          mkdir -p "$CA_HOME/newcerts"
          mkdir -p "$CA_HOME/private"
          chmod 700 "$CA_HOME/private"
          if [ ! -f "$CA_HOME/index.txt" ]; then
            touch "$CA_HOME/index.txt"
          fi
          if [ ! -f "$CA_HOME/serial" ]; then
            echo 01 > "$CA_HOME/serial"
          fi
      - name: Get CA key
        env:
          CA_KEY: ${{ secrets.CA_KEY }}
        run: |
          cat <<EOF > "$CA_HOME/private/key.pem"
          $CA_KEY
          EOF
          chmod 600 "$CA_HOME/private/key.pem"
      - name: Sign certificate
        env:
          CA_KEY_SECRET: ${{ secrets.CA_KEY_SECRET }}
        run: |
          ls -la "$CA_HOME/private/key.pem"
          openssl rsa -in "$CA_HOME/private/key.pem" -passin "env:CA_KEY_SECRET" -check -noout
          openssl ca \
            -config "ca/openssl.cnf" \
            -extensions "v3_svr" \
            -name "${{ needs.read_config.outputs.ca }}_ca" \
            -passin "env:CA_KEY_SECRET" \
            -in "hosts/${{ env.host }}/${{ env.host }}.csr" \
            -out "hosts/${{ env.host }}/${{ env.host }}.pem" \
            -batch
      - name: Create chained certificate
        run: |
          cat hosts/${{ env.host }}/${{ env.host }}.pem >> hosts/${{ env.host }}/certificate-chain.pem
          cat "$CA_HOME/certs/intermediate.pem" >> hosts/${{ env.host }}/certificate-chain.pem
          #cat "root.pem" >> hosts/${{ env.host }}/certificate-chain.pem
      - name: Save bundle
        uses: actions/upload-artifact@v4
        with:
          name: certificate-bundle
          path: |
            hosts/${{ env.host }}/${{ env.host }}.pem
            ca/${{ needs.read_config.outputs.ca }}/certs/intermediate.pem
            hosts/${{ env.host }}/certificate-chain.pem
      - name: Remove private files
        run: rm -f "$CA_HOME/private/*"
      
#
#  cleanup:
#    name: Cleanup
#    runs-on: ubuntu-latest


#- name: Commit CSR
#        uses: EndBug/add-and-commit@v9.1.4
#        with:
#          add: hosts/testhost/${{ steps.readfile.outputs.fqdn }}.csr
#          author_name: Steve
#          author_email: steve.roberts@essarsoftware.co.uk
#          fetch: false
#          message: "Create CSR for ${{ steps.readfile.outputs.fqdn }}"